#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
#yabai -m config focus_follows_mouse          autoraise
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_border                off
yabai -m config window_border_width          6
#yabai -m config active_window_border_color   0xff775759
#yabai -m config normal_window_border_color   0xff555555
yabai -m config active_window_border_color   0xff8CABC8
yabai -m config normal_window_border_color   0xff434c5e
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap


# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  2
#yabai -m config bottom_padding               5
yabai -m config bottom_padding               32
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   4



# space labels
yabai -m space 1 --label code
yabai -m space 2 --label web
yabai -m space 3 --label research
yabai -m space 4 --label office
yabai -m space 5 --label enjoy
yabai -m space 6 --label more
yabai -m space 7 --label seven
yabai -m space 8 --label eight
yabai -m space 9 --label nine
yabai -m space 10 --label ten

# space rules
yabai -m rule --add app="(Code|iTerm)" space=^code
yabai -m rule --add app="^(Mail|Finder|Safari|Google Chrome)$" space=^web
yabai -m rule --add app="^(Zotero|PDF Expert)$" space=^research
yabai -m rule --add app="^(Microsoft PowerPoint|Microsoft Excel)$" space=^office manage=off
yabai -m rule --add app="^(QQ|WeChat|QQ音乐|优酷)$" space=^enjoy manage=off
yabai -m rule --add app="^(EuDic|System Preferences|Parallels Desktop)$" space=^more manage=off
# automatically create 6 windows
while [ $(yabai -m query --displays | jq '.[].spaces' | jq length) -lt 6 ]
do
    yabai -m space --create; done
done
# float system preferences. Most of these just diable Yabai form resizing them.
#yabai -m rule --add app="^1Password 7$" manage=off
# S K E T C H Y B A R  E V E N T S
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"
# yabai signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=space_changed action="landscape"

echo "yabai configuration loaded.."

